### ISSUE TITLE
resuse my lecture notes

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-tutorial-sea-2018#1]
For my research computing class, I made this lecture
https://rabernat.github.io/research_computing/xarray.html

and this homework assignment
https://rabernat.github.io/research_computing/assignment-8-xarray.html

Raw notebooks available here
https://github.com/rabernat/research_computing/blob/master/content/lectures/python/xarray.ipynb
https://github.com/rabernat/research_computing/blob/master/content/Assignments/Assignment_8.ipynb

If these are useful, please reuse / modify however you want.

**Comment by jhamman** [comment]
Thanks @rabernat. We'll take a look.
