### ISSUE TITLE
Outline Topics

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo-tutorial-sea-2018#3]
@jhamman I have a question for you about topics for the tutorial.  Do you feel like we need to discuss:

1. Distributed futures
2. Bags / DataFrames (i.e., just concentrate on Arrays)

And related, do you want to cover the xarray.apply_ufunc?  I doubt I am as expert in that as you.

**Comment by jhamman** [comment]
I don't feel like either of the two items you listed need to be covered in much, if any detail. I will cover `apply_ufunc` and mention the integration with dask.

**Comment by kmpaul** [comment]
Great.  That's what I was thinking, too.
