### ISSUE TITLE
Tutorial links are broken

### ISSUE THREAD

**Issue by ahuang11** [pangeo-data/pangeo-tutorial-sea-2018#5]
Just wanted to point out that the links to 2.1, 2.2, 2.3, 2.4, 2.5, and 2.7 are broken.
https://github.com/pangeo-data/pangeo-tutorial-sea-2018/blob/master/notebooks/0.0.introduction.ipynb

![image](https://user-images.githubusercontent.com/15331990/42661507-3813c320-85e3-11e8-85a8-3aa78ce4e0a6.png)

Cool tutorial by the way!

**Comment by kmpaul** [comment]
Thanks for the compliment AND the bug pointers!  I will fix them shortly!

**Comment by kmpaul** [comment]
Fixed with https://github.com/pangeo-data/pangeo-tutorial-sea-2018/commit/aea5a2978f8997923260557145fd9d2864c3e22a
